#! /bin/bash


# Import directories, and update
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update

# Install software with apt-get, forcing any 'are you sure' type questions
sudo apt-get install -y git
sudo apt-get install -y python-pip
sudo apt-get install -y python-dev
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo apt-get install -y oracle-java8-installer

# Install software with pip
sudo pip install virtualenv

# Other software ... Text editors, IDEs, etc.
wget http://c758482.r82.cf2.rackcdn.com/Sublime\ Text\ 2.0.2\ x64.tar.bz2
tar vxjf Sublime\ Text\ 2.0.2\ x64.tar.bz2

# Configure Github
git config --global user.name "JohnDevitt"
git config --global user.email "johndevittire@gmail.com"
git clone https://github.com/JohnDevitt/StartupScript ~/Desktop/StartupScript
git clone https://github.com/JohnDevitt/montagemaker.git
